### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ZzZombo** [jptrrs/OpenTheWindows#1]
- Do windows keep the elements out? So that things inside do not deteriorate, and temperature stays at desired levels.
- Can you fire through them? Do they break if you do?
- Can you move through them?
- Do they separate rooms?
- How much cover do they provide?

Nice mod, BTW, always wanted real windows. My first gripe with the game on the first playthrough was the lack of windows!

**Comment by jptrrs** [comment]
Hi ZzZombo!

- "Do windows keep the elements out? So that things inside do not
deteriorate, and temperature stays at desired levels."
- - Yes! I'm working on an option to make windows also act like vents, that
you'll be able to toggle on/off. But for now, they're completely sealed.
-
- "Can you fire through them? Do they break if you do?"
- - Presently, no. But I'm putting that in my to-do list!
-
- "Can you move through them?"
- - Nope.
-
- "Do they separate rooms?"
- - Yes. But if placed between roofed rooms they won't produce any natural
light

"How much cover do they provide?"
- - Presently, full cover. I might change that when I improve the
fire-through characteristics.

" always wanted real windows "
- Me too ;)

Thanks for these ideas and for trying it out. Please keep in mind it's
still a work in progress!
